# VictoriaMetrics k8s stack
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack 
  namespace: observability
spec:
  interval: 1h
  releaseName: vm
  chart:
    spec:
      chart: victoria-metrics-k8s-stack # https://artifacthub.io/packages/helm/victoriametrics/victoria-metrics-k8s-stack
      version: "0.95.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: observability
      interval: 1h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    fullnameOverride: vm
    
    # installed separately in ../../controllers.
    victoria-metrics-operator: 
      enabled: false
      
    # VM metrics agent scrapes application + cluster targets via VMServiceScrape/VMNodeScrape
    vmagent:
      enabled: true
  
    # use single node installation
    vmsingle: 
      enabled: true
      spec:
        retentionPeriod: 7d
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi

    # VictoriaLogs single node instance installation
    vlsingle:
      enabled: true
      spec:
        retentionPeriod: 7d
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi

    # VictoriaLogs collector
    vlagent:
      enabled: true

    vmalert:
      enabled: true
    alertmanager:
      enabled: true
      config:
        route:
          receiver: blackhole
          group_by:
            - alertname
            - namespace
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          routes:
            - matchers:
                - severity="critical"
              receiver: blackhole
            - matchers:
                - severity="warning"
              receiver: blackhole
        receivers:
          - name: blackhole # - nothing will ring; otherwise would need to use something like PagerDuty or at least a webhook
        # supress warning notifications if an app is down
        inhibit_rules:
          - source_matchers:
              - alertname="AppTargetDown"
            target_matchers:
              - severity="warning"
            equal:
              - job

    grafana:
      enabled: true
      adminPassword: admin # will do for assignment purposes; otherwise should use secrets
      grafana.ini:
        grafana-apiserver:
          preferred_api_version: dashboard.grafana.app/v1 # To be able to export V1 dashboard specs from the grafana API; compatible with the sidecar
      plugins:
        - victoriametrics-logs-datasource
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          memory: 1Gi

    prometheus-node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true
      # drop everything except pods, deployments and nodes
      collectors:
        - pods
        - deployments
        - nodes

    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    kubeApiServer:
      enabled: false
    coreDns:
      enabled: false
    defaultDashboards:
      enabled: false
    defaultRules:
      create: false
    syncJob:
      enabled: false
