apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - helmrelease-vmstack.yaml
  - dashboard-ml-api.yaml
  - dashboard-backend-api.yaml
  - vmrules-apps.yaml
  - vmrules-cluster.yaml
