receivers:
  file_log:
    include:
      - /var/log/pods/*/*/*.log
    exclude:
      - /var/log/pods/observability_otel-collector-logs*/*/*.log # Exclude self logs of the log collector
    start_at: end # read from the tail of the log file; to not duplicate the logs during restart and 
    include_file_path: true
    include_file_name: false
    storage: file_storage
    operators:
      # CRI/JSON container log parsing
      - type: container
        id: container-parser
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25
  filter/health:
    error_mode: ignore
    logs:
      log_record:
        - 'IsMatch(body, "GET /(health|ready) HTTP[^\"]*\" 2[0-9][0-9]")'
  k8s_attributes:
    auth_type: serviceAccount
    extract:
      metadata:
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.container.name
        - k8s.node.name
        - k8s.deployment.name
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.uid # use pod UID as name OR
      - sources:
          - from: resource_attribute
            name: k8s.pod.name # use pod name as name
  resource:
    attributes:
      - key: k8s.cluster.name
        value: devops-cs
        action: upsert
  batch: {}
exporters:
  otlp_http/victorialogs:
    logs_endpoint: http://vlsingle-vm.observability.svc.cluster.local:9428/insert/opentelemetry/v1/logs
    compression: gzip
    encoding: proto
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  file_storage:
    directory: /var/lib/otelcol-logs
    create_directory: true
service:
  extensions:
    - health_check
    - file_storage
  pipelines:
    logs:
      receivers:
        - file_log
      processors:
        - memory_limiter
        - filter/health
        - k8s_attributes
        - resource
        - batch
      exporters:
        - otlp_http/victorialogs
